In [4]:
# Anything in this notebook will be to test out Numpy from the SciPy and NumPy book

# Chapter 2.1 the actual start of the book
## NumPy Arrays

Usually for operating on items in a list or dictionary
Python does this with iterative loops which is inefficient in Python. 

NumPy lets us overcome this by providing a data storage object called **ndarray**.

The **ndarray** is similar to lists but rather than being highly flexible by storing different types of objects in one list, ONLY THE SAME TYPE OF ELEMENT can be stored in each column. (Normal Python lists can contain anything, strings, dataframes, lists, integers, floats) Despite **ndarray** being restricted to just one datatype, it wins hands down when it comes to operation times. 

We're going to time the commands with %timeit a Python 'magic' command which outputs the speed/time of the command run

In [1]:
import numpy as np

# Create an array with 10^7 elements
arr = np.arange(1e7)

# Converting ndarray to list
larr = arr.tolist()

# Lists cannot be default broadcast,
# so a function is coded to emulate
# what an ndarray can do.

In [6]:
def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar
    return alist

In [8]:
# Using IPython's magic timeit command
%timeit arr * 1.1

50 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit list_times(larr, 1.1)

1.85 s ± 68.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


the ndarray operation (first one) is ~25 times faster in the loop. If we need to do linear alegbra. We will use the **matrix** object. The usual behavior is similar to the R matrix

In [4]:
# Creating a 3D numpy array
arr = np.zeros((3,3,3))

In [7]:
# Trying to convert array to a matrix, which will not work
#mat = np.matrix(arr)
# this results in a Value Error: shape too large to be a matrix
# If you're working with matrices, keep this in mind

# 2.1.1 Array Creation and Data Typing
## Many ways to crete an array in NumPy, we will discuss the most useful ones

In [13]:
# First we make a list and then wrap it with the np.array() function
alist = [1, 2, 3]
arr = np.array(alist)
arr

array([1, 2, 3])

In [14]:
# Creating an array of zeros with five elements
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [15]:
# What if we want to create an array going from 0 to 100?
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
# Or 10 to 100?
arr = np.arange(10, 100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [20]:
# If you want 100 steps(values) from 0 to 1...
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [23]:
# Of if you want to generate an array from 1 to 10
# in log10 space in 100 steps...
arr = np.logspace(0, 1, 100, base = 10.0)
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [24]:
# Creating a 5x5 array of zeros (an image)
image = np.zeros((5,5))
image

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# Creating a 5x5x5 cube of 1's
# The astype() method sets the array with integer elements
cube = np.zeros((5, 5, 5)).astype(int) + 1
cube

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [26]:
# Or even simpler with 16-bit floating-point precision...
cube = np.ones((5, 5, 5)).astype(np.float16)
cube

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

If you're using 64bit Python then the elements in the array use 64-bit precision. This precision takes a fair chunk of memory and is not always necessary. You can specify the bit depth when creating arrays by setting the data type parameter (dtype) to int, np.float16, np.float32, np.float64. Let's look at some examples:

In [9]:
# Array of zero integers
arr = np.zeros(2, dtype = int) # Change this to the options specified above 
arr

# Not part of the book but we can use sys to determine the size of the object
import sys
sys.getsizeof(arr)

104

Now that we've created arrays we can reshape them in many other ways. If we have a 25 element array, we can make it a 5x5 array, or we could make a 3D array from a flat array

In [13]:
# Creating an array with elements from 0 to 999
arr1d = np.arange(1000)
arr1d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [14]:
# Now reshaping the array to a 10x10x10 3D Array
arr3d = np.reshape(arr1d, (10, 10, 10))
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [15]:
# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (10, 10, 10))

In [16]:
# Inversely, we can flatten arrays
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()

In [17]:
arr1d.shape

(10000,)

the restructured arrays above are just different views of the same data in memory. This means if you modify one of the arrays, it will modify the others.

For example, if you set the first element of arr1d from the example above to be 1, then the first element of arr3d will also become 1. 

If you don't want this to happen, then use the **numpy.copy** function to separate the arrays memory-wise

# 2.1.2 Record Arrays

Arrays are good for integers and floats but sometimes we need to use more complex data structures where columns are composed of different data types. 

In research journal publications, tables are commonly structured so that some columns may have string characters for identification and floats for numerical quantities. Being able to store this type of information is very beneficial. In NumPy, there is the **np.recarray()**

Constructing a **recarray** for the first time can be confusing so we'll go over the basics first. 

In [20]:
# Creating an array of zeros and defining the column types
recarr = np.zeros((2, ), dtype = ('i4, f4, a10'))
toadd = [(1, 2., 'Hello'), (2, 3., 'World')]
recarr[:] = toadd
recarr

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

the dtype optional argument is defining the types designated for the first to third columns, where:
 i4 corresponds to a 32-bit integer
 f4 corresponds to a 32-bit float
 a10 corresponds to a string 10 characters long

Details on how to define more types can be found in NumPy documnetation. This example illustrates what the recarray looks like:

(Its hard to see how we could populate such an array easily. Thankfully, Python has a global function called zip that will create a list of typles like we see above for the toadd object. We can show how to use zip to populate the same recarray)

In [29]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2, ), dtype=('i4, f4, a10'))

# Now creating the columns we want to put in the recarray
col1 = np.arange(2) + 1
col2 = np.arange(2, dtype = np.float32)
col3 = ['Hello', 'World']

# Here we create a list of tuples that is identical to the previous toadd list
toadd = list(zip(col1, col2, col3)) # added list() because zip() alone wasn't working

# Assigning values to recarr
recarr[:] = toadd

In [28]:
# Assigning names to each column, which are now by default called 'f0', 'f1', 'f2'
recarr.dtype.names = ('Integers', 'Floats', 'Strings')

# If we want to access one of the columns by its name, we can do the following
recarr['Integers'] # Changed this to brackets instead of parenthesis 


array([1, 2])

# 2.1.3 Indexing and Slicing

Python index begins at zero and the NumPy arrays follow that. 
When indexing lists in Python, we normally do the following for a 2 x 2 object: 

In [31]:
alist = [[1,2], [3,4]]

# To return the (0,1) element we must index as shown below
alist[0][1]

2

If we want to return the right-hand column in NumPy indexing follows a more convenient syntax

In [33]:
# Converting the list defined above into an array
arr = np.array(alist)

# To return the (0,1) element we use ...
arr[0 , 1]

# Now to acces the last column, we simply use ...
arr[: , 1]

# Accessing the columns is achieved in the same way, 
#  which is the bottom row
arr[1 , :]

array([3, 4])

Sometimes there are more complexs indexing schemes required. Such as conditional indexing. The most commonly used type is **numpy.where()** with this function you can return the desired indices from an array, regardless of its dimensions, based on some condition(s)

In [34]:
# Creating an array
arr = np.arange(5)

# Creating the index array
index = np.where(arr > 2)
index

(array([3, 4], dtype=int64),)

In [36]:
# Creating the desired array
new_arr = arr[index]
new_arr

array([3, 4])

However, you may want to remove specific indices instead. To do this you can use **numpy.delete()** The required inputs are the array and indices that you want to remove

In [37]:
# We use the previous array
new_arr = np.delete(arr, index)
new_arr

array([0, 1, 2])

Instead of using the **numpy.where()** function, we can use a simple boolean array to return specific elements

In [38]:
index = arr > 2
print(index)

[False False False  True  True]


In [40]:
new_arr = arr[index]
new_arr

array([3, 4])

## Which method is faster? 
Boolean indexing is faster for a large number of elements. Additionally, you can easily invert True and False objects in an array by '~ index' a technique that is far faster than redoing the **numpy.where()** function

In [41]:
new = arr[~index]
new

array([0, 1, 2])

# 2.2 Boolean Statements and NumPy Arrays