In [4]:
# Anything in this notebook will be to test out Numpy from the SciPy and NumPy book

# Chapter 2.1 the actual start of the book
## NumPy Arrays

Usually for operating on items in a list or dictionary
Python does this with iterative loops which is inefficient in Python. 

NumPy lets us overcome this by providing a data storage object called **ndarray**.

The **ndarray** is similar to lists but rather than being highly flexible by storing different types of objects in one list, ONLY THE SAME TYPE OF ELEMENT can be stored in each column. (Normal Python lists can contain anything, strings, dataframes, lists, integers, floats) Despite **ndarray** being restricted to just one datatype, it wins hands down when it comes to operation times. 

We're going to time the commands with %timeit a Python 'magic' command which outputs the speed/time of the command run

In [2]:
import numpy as np

# Create an array with 10^7 elements
arr = np.arange(1e7)

# Converting ndarray to list
larr = arr.tolist()

# Lists cannot be default broadcast,
# so a function is coded to emulate
# what an ndarray can do.

In [6]:
def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar
    return alist

In [8]:
# Using IPython's magic timeit command
%timeit arr * 1.1

50 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit list_times(larr, 1.1)

1.85 s ± 68.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


the ndarray operation (first one) is ~25 times faster in the loop. If we need to do linear alegbra. We will use the **matrix** object. The usual behavior is similar to the R matrix

In [4]:
# Creating a 3D numpy array
arr = np.zeros((3,3,3))

In [7]:
# Trying to convert array to a matrix, which will not work
#mat = np.matrix(arr)
# this results in a Value Error: shape too large to be a matrix
# If you're working with matrices, keep this in mind

# 2.1.1 Array Creation and Data Typing
## Many ways to crete an array in NumPy, we will discuss the most useful ones

In [13]:
# First we make a list and then wrap it with the np.array() function
alist = [1, 2, 3]
arr = np.array(alist)
arr

array([1, 2, 3])

In [14]:
# Creating an array of zeros with five elements
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [15]:
# What if we want to create an array going from 0 to 100?
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])